# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71f27e472819dbd6d5e7ae266b7366d02911d17b2ec9cfb99613840b9296f6bf000b89498160891d30fb4745eaa6cbbc8c691e34f3dbf5ec8f3fccfcdaff1a85

test:
  secret_key_base: 80fe39f1f371da241242e51e1fbc2c3dca1398d42173659ac29622baf3f9b0286024ca95a9beed3c5ee58d1b31e9a6183e231cb37217bf2f60b1c6c785cfc357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
